name: Build

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0" # Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    name: Prepare
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - latest
          - nightly
          - 1.0.0
    steps:
    -
      name: Checkout release
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - 
      name: Generate version number
      id: versions
      run: |
        echo ::debug::Generating platform version
        offset=$(git rev-list --count master)
        echo ::set-output name=TAG::$offset
    - 
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - 
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        build-args: |
          CRYSTAL_VERSION: ${{ matrix.crystal }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/drivers-spec:crystal-${{matrix.crystal}}
        labels: |
          org.opencontainers.image.vendor=Place Technology Limited
          org.opencontainers.image.version=${{ steps.versions.outputs.TAG }}

    - 
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
